#默认的配置文件
spring:
  profiles:
    active: dev
#指定对应的log文件
logging:
  config: classpath:logback-core.xml



---
#配置对应的模版
spring:
  profiles: dev
  datasource:
    druid:
      url:  jdbc:mysql://192.168.0.108:3306/testMybaits
      password: root
      username: root
      driver-calss-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 20
      max-wait: 6000 #等待的时间
      db-type: com.alibaba.druid.pool.DruidDataSource
      time-between-connect-error-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 400000  #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query:  SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true  #打开 PS Cache ，并且指定每个连接上 PSCache 的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat  #＃配置监控统计拦截的 filters ，去掉后监控界面的 SQL 无法统计， wall 用于防火墙
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      use-global-data-source-stat:  true  #合并多个 Dru dDataSource 的监控数据
      connect-properties:    #通过 connectProperties 属性来打开 mergeSql 功能，慢 SQL 记录
        druid.stat.mergeSql: true
        druid.stat.slowSqlMillis: 500

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8 #最大的连接数
        max-wait: -1ms  #时间
        max-idle: 9 #最大空闲数
        min-idle: 1 #最小空闲数




mybatis:
  mapper-locations:
      - classpath:mapper/UsersDao.xml
      - classpath:mapper/TomDao.xml

knife4j:
  enable: true
  openapi:
    title: CRUD的测试文档
    description:  测试描述
    email: 605501479@foxmail.com
    concat: 测试
    version: v4.0
    license: Apache 2.0
    group:
      test1:
        group-name: boot测试
        api-rule: package
        api-rule-resources:
          - com.zr.sf.doy22.controller

